'use client';
import Image from 'next/image';
import { useEffect, useMemo, useState } from 'react';
import { featured, profile, skills, experience, education } from '../data/portfolio';

type Repo={id:number;name:string;html_url:string;description:string|null;language:string|null;stargazers_count:number;forks_count:number;topics?:string[];updated_at:string};
const cats=['All','AI / ML','GenAI','Full Stack','Backend','Data'];
function infer(r:Repo){const s=(r.name+' '+(r.description||'')+' '+(r.topics||[]).join(' ')).toLowerCase();if(/rag|llm|gemini|genai|agent|voicebot|nlp|resume-screener/.test(s))return 'GenAI';if(/react|next|node|mern|portal|shop|chat|scheduler|hms/.test(s))return 'Full Stack';if(/flask|fastapi|api|backend|pipeline|docker/.test(s))return 'Backend';if(/pandas|analysis|analytics|forecast|prediction|stock|fraud|retinopathy|sentiment|ipl|supply|churn|attrition|ml/.test(s))return 'AI / ML';return 'Data'}
export default function Home(){
 const emailHref=`https://mail.google.com/mail/u/0/?view=cm&fs=1&to=${encodeURIComponent(profile.email)}`;
 const phoneHref=`tel:${profile.phone.replace(/[^+\d]/g,'')}`;
 const whatsappHref=`https://wa.me/${profile.phone.replace(/\D/g,'')}`;
 const [repos,setRepos]=useState<Repo[]>([]); const [filter,setFilter]=useState('All'); const [q,setQ]=useState('');
 useEffect(()=>{fetch('https://api.github.com/users/Nithish464/repos?per_page=100&sort=updated').then(r=>r.json()).then(d=>Array.isArray(d)&&setRepos(d)).catch(()=>{});},[]);
 const list=useMemo(()=>repos.filter(r=>(filter==='All'||infer(r)===filter)&&((r.name+' '+(r.description||'')).toLowerCase().includes(q.toLowerCase()))),[repos,filter,q]);
 return <main>
  <nav className="nav"><a className="brand" href="#home">NK<span>.</span></a><div className="navlinks"><a href="#about">About</a><a href="#skills">Skills</a><a href="#experience">Experience</a><a href="#projects">Projects</a><a href="#contact">Contact</a></div><a className="navcta" href="/resume.pdf" target="_blank" rel="noopener noreferrer">Resume ↗</a></nav>
  <section id="home" className="hero wrap"><div className="heroCopy"><div className="eyebrow">AVAILABLE FOR OPPORTUNITIES · 2026</div><h1>Building <span>intelligent</span><br/>products that ship.</h1><p className="lead">I’m Nithishkumar — a Full-Stack Developer and Data Science graduate focused on AI, GenAI, scalable APIs and polished product experiences.</p><div className="actions"><a className="primary" href="#projects">Explore Projects ↓</a><a className="ghost" href={profile.github} target="_blank">GitHub ↗</a></div><div className="miniStats"><div><b>40+</b><small>Repositories</small></div><div><b>4</b><small>Featured Builds</small></div><div><b>AI + Web</b><small>Core Focus</small></div></div></div><div className="portraitWrap"><div className="orb orb1"/><div className="orb orb2"/><div className="portrait"><Image src="/profile.jpg" alt="Nithishkumar K" fill priority sizes="420px"/></div><div className="floatCard"><span>✦</span><div><b>AI × Full Stack</b><small>Build · Integrate · Ship</small></div></div></div></section>
  <section id="about" className="section wrap"><div className="sectionHead"><span>01</span><h2>About</h2></div><div className="aboutGrid"><div><p className="bigText">I turn ideas into usable software — from responsive interfaces and REST APIs to RAG systems, LLM workflows and data-driven applications.</p><p className="aboutSummary">I’m a Data Science graduate with hands-on experience across full-stack development, backend engineering, analytics, AI and GenAI. I enjoy designing reliable APIs, building responsive products, integrating LLMs and turning complex data into practical solutions. My projects span asynchronous systems, RAG-based knowledge assistants, AI-powered applications, authentication and role-based platforms.</p><p className="aboutSummary">I’m currently focused on opportunities where I can contribute as a Full-Stack, Backend, AI or GenAI Developer while continuing to build production-minded software.</p></div><div className="aboutCard"><div><b>Based in</b><span>Coimbatore, India</span></div><div><b>Education</b><span>Integrated M.Sc. Data Science</span></div><div><b>Focus</b><span>Full Stack · AI · GenAI</span></div></div></div></section>
  <section id="skills" className="section wrap"><div className="sectionHead"><span>02</span><h2>Technical Stack</h2></div><div className="skillGrid">{Object.entries(skills).map(([k,v])=><div className="skillCard" key={k}><h3>{k}</h3><div className="chips">{v.map(x=><span key={x}>{x}</span>)}</div></div>)}</div></section>
  <section id="experience" className="section wrap"><div className="sectionHead"><span>03</span><h2>Experience</h2></div><div className="timeline">{experience.map((e,i)=><article className="exp" key={e.company}><div className="dot">0{i+1}</div><div className="expBody"><div className="expTop"><div><h3>{e.role}</h3><p>{e.company}</p></div><time>{e.period}</time></div><p className="muted">{e.text}</p><div className="chips">{e.tags.map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div></section>
  <section id="projects" className="section wrap"><div className="sectionHead"><span>04</span><h2>Selected Projects</h2><p>Featured builds first. Every project links directly to GitHub.</p></div><div className="featuredGrid">{featured.map((p,i)=><a className="projectCard" href={`https://github.com/Nithish464/${p.repo}`} target="_blank" key={p.repo}><div className="projectNum">0{i+1}</div><div className="projectArrow">↗</div><div className="projectMeta">{p.category}</div><h3>{p.title}</h3><p>{p.desc}</p><div className="chips">{p.tech.map(t=><span key={t}>{t}</span>)}</div></a>)}</div>
   <div className="allProjects"><div className="allTop"><div><div className="eyebrow">FULL REPOSITORY SHOWCASE</div><h3>All GitHub Projects</h3></div><div className="repoCount">{repos.length || '40+'} repos</div></div><div className="filters">{cats.map(c=><button className={filter===c?'active':''} onClick={()=>setFilter(c)} key={c}>{c}</button>)}<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search projects..."/></div><div className="repoGrid">{list.map(r=><a className="repoCard" href={r.html_url} target="_blank" key={r.id}><div className="repoTop"><span className="langDot"/> {r.language||'Project'}<span>↗</span></div><h4>{r.name.replaceAll('-',' ')}</h4><p>{r.description||'Explore this repository on GitHub.'}</p><div className="repoFoot"><span>★ {r.stargazers_count}</span><span>⑂ {r.forks_count}</span><span>{infer(r)}</span></div></a>)}</div></div>
  </section>
  <section className="section wrap"><div className="sectionHead"><span>05</span><h2>Education</h2></div><div className="education">{education.map(e=><div className="edu" key={e[0]}><div><h3>{e[0]}</h3><p>{e[1]}</p></div><span>{e[2]}</span></div>)}</div></section>
  <section id="contact" className="contact wrap"><div className="eyebrow">LET’S BUILD SOMETHING</div><h2>Have a problem worth solving?</h2><p>Open to full-stack, backend, AI and GenAI opportunities.</p><div className="contactActions"><a className="primary" href={emailHref} target="_blank" rel="noopener noreferrer">Email Me ↗</a><a className="ghost" href={phoneHref}>Call Me ↗</a><a className="ghost" href={whatsappHref} target="_blank" rel="noreferrer">WhatsApp ↗</a><a className="ghost" href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a><a className="ghost" href={profile.leetcode} target="_blank" rel="noreferrer">LeetCode ↗</a></div><div className="contactDetails"><a href={emailHref} target="_blank" rel="noopener noreferrer">✉ {profile.email}</a><a href={phoneHref}>☎ {profile.phone}</a><span>⌖ {profile.location}</span></div></section>
  <footer><span>© 2026 Nithishkumar K</span><span>Designed & built with intent.</span><span><a href={profile.github}>GitHub</a> · <a href={emailHref} target="_blank" rel="noopener noreferrer">Email</a></span></footer>
 </main>
}
